include_recipe "pivotal_workstation::java"
include_recipe "pivotal_workstation::intellij_ultimate_edition"
include_recipe "scala_workstation::akka"
include_recipe "scala_workstation::sbt"
include_recipe "scala_workstation::giter8"
