include_recipe "pivotal_workstation::bash_it"
include_recipe "pivotal_workstation::bash4"
include_recipe "pivotal_workstation::bash_completion"
include_recipe "scala_workstation::git_config_global_defaults"
include_recipe "pivotal_workstation::github_for_mac"
include_recipe "pivotal_workstation::gitx"
include_recipe "pivotal_workstation::tig"
include_recipe "pivotal_workstation::global_environment_variables"
include_recipe "pivotal_workstation::homebrew"
include_recipe "pivotal_workstation::iterm2"
include_recipe "pivotal_workstation::unix_essentials"
include_recipe "pivotal_workstation::vagrant"
include_recipe "pivotal_workstation::vim"
include_recipe "pivotal_workstation::virtualbox"
include_recipe "pivotal_workstation::workspace_directory"
include_recipe "pivotal_workstation::flycut"
include_recipe "pivotal_workstation::ack"
include_recipe "pivotal_workstation::tcp_keepalive"
include_recipe "pivotal_workstation::xquartz"
include_recipe "pivotal_workstation::wget"
include_recipe "scala_workstation::solarized_terminal_settings"

# include_recipe "pivotal_workstation::keycastr"
# include_recipe "pivotal_workstation::speed_up_mission_control_animations"
